### ISSUE TITLE
Plugin doesn't load pre-existing medals

### ISSUE THREAD

**Issue by tyrope** [SilPho/medal-collection#1]
Heya Silpho,

As can be seen in this screenshot, I have many more medal in the current campaign alone than your plugin determines.
It didn't load my full collection initially, but when when I tried to improve a couple of medals I did have it now assumes the local collection is complete.

![image](https://github.com/SilPho/medal-collection/assets/516490/55a765d3-5f49-4236-8535-0546bb5334ce)

Perhaps an idea would be to add a "recheck collection" button to the settings to consider the locally sourced information incomplete. This will also help people who play on more than 1 device.

**Comment by SilPho** [comment]
Hey Tyrope,

Thanks for the feedback. There is an option in the OpenPlanet "Plugins" dropdown to recheck your medal collection. Clicking this will update with any missing information.

![image](https://github.com/SilPho/medal-collection/assets/22282491/186ebab8-a5df-4839-b176-ef60340e1bed)

The plugin is supposed to do this by default when it first gets installed, so I'll do some more tests to try and find out why that's not happening.

**Comment by tyrope** [comment]
Good to know that feature exists. Unfortunately the core of this bug (it not loading my pre-existing medals) is still valid.

![image](https://github.com/SilPho/medal-collection/assets/516490/ee78293d-f139-43a0-861c-6c26fc222a88)

This is as far as the recheck goes. And it's been running for 5 minutes... So I'd assume that at the very least authentication would've completed, printing the debug on this line: [Misc.as#L41](https://github.com/SilPho/medal-collection/blob/main/Misc.as#L41)

**Comment by SilPho** [comment]
Thanks, that's a really helpful bug report.

I may have identified why the authentication is failing, it seems the plugin is checking for authentication it doesn't need.

A new version has been submitted and ~~will be released once it passes a review (Usually within a few days)~~ should be available for download now.

**Comment by tyrope** [comment]
Fixed! :)
