### ISSUE TITLE
WRs?

### ISSUE THREAD

**Issue by HelldiverAgent** [SilPho/medal-collection#2]
Really good plugin, works very well. Whar I just wondered was, if you can check finished or even played maps, can you also check world records? Would be cool to have this since I for myself lost track of how many I've got. Maybe you could toggle it in the options then aswell.

I hope this is the right way of submitting suggestions since im new on Github and couldn't find your discord.
Thanks in advance :)

**Comment by SilPho** [comment]
I'd love this feature for myself as well (even though I only have 1 or 2), but it's harder to handle world records because you can lose them later on; unlike medal counts, which only go up.

That said, I'll keep it in mind if I get some time to dig into it.

**Comment by SilPho** [comment]
It took a while, but the plugin does now supports World Records! As well as continental, national and regional records.

It will take a while, potentially a long while, for the plugin to scan through your existing map finishes to see if they are record-worthy, but it will get there eventually.
