### ISSUE TITLE
Warrior medals support

### ISSUE THREAD

**Issue by XenoJiiva0053** [SilPho/medal-collection#3]
If possible it would be really nice with support for warrior medals

**Comment by SilPho** [comment]
Love the idea. I'll see what I can do (No promises on how long it might take though)

**Comment by SilPho** [comment]
Version 1.5 of the plugin has been released, which now includes Warrior Medal support! You'll have to use the "Re-check Warrior medals" button in the dropdown menu to retroactively find your warrior medal progress.

If you find any problems with this implementation, please open a new issue
