### ISSUE TITLE
Rechecks

### ISSUE THREAD

**Issue by Doggodoggo3213** [SilPho/medal-collection#4]
I just downloaded the plugin and none of my medals appeared, even after I waited a few minutes. I saw that I could recheck my medals, and there was a script exception.

If it is helpful, I'll paste the log message

Unable to fetch https://prod.trackmania.core.nadeo.online/map
MedalCollection.op/:/Misc.as (line 61, column 9)
 #.0 string getfromUrl(string&in url) (MedalCollection.op/:/Misc.as line 61)
 #.1 dictionary getUserMedals() (MedalCollection.op/:/RecordChecker.as line 23)
 #.2 void getMapMedals() (MedalCollection.op/:/RecordChecker.as line 10)

**Comment by SilPho** [comment]
It seems Nadeo have changed something that has fundamentally broken this plugin. What a pain. I'll see what I can do to fix this. Sorry for the inconvenience.

**Comment by SilPho** [comment]
Version 1.5 of the plugin has now submitted, which should fix this. I will close this issue for now, but please leave a comment if anything is still broken.
